version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - C:\SpringDataRest\prometheus\promotheus.yml:/etc/prometheus/prometheus.yml  # Chemin relatif pour le fichier de configuration
    ports:
      - "9091:9090"  # Port par défaut pour Prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Port par défaut pour Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
