global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # Chemin pour les métriques
    static_configs:
      - targets: ['host.docker.internal:8080']  # Utilisez host.docker.internal pour accéder à l'hôte depuis Docker sur Windows/Mac
